name: build-c18
on:
  push:
    branches:
      - master
    paths:
      - 'files/*'
      - 'runtimes/c18/*'
      - '.github/workflows/build-c18.yml'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy files
        run: cp files/* runtimes/c18/
      - name: Build Image
        uses: docker/build-push-action@v1.0.1
        with:
          repository: pnoj/executor-c18
          path: runtimes/c18
          add_git_labels: true
          tag_with_sha: true
          tags: latest
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
