name: build-java8
on:
  push:
    branches:
      - master
    paths:
      - 'files/*'
      - 'runtimes/java8/*'
      - '.github/workflows/build-java8.yml'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy files
        run: cp files/* runtimes/java8/
      - name: Build Image
        uses: docker/build-push-action@v1.0.1
        with:
          repository: pnoj/executor-java8
          path: runtimes/java8
          add_git_labels: true
          tag_with_sha: true
          tags: latest
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
