name: build-text
on:
  push:
    branches:
      - master
    paths:
      - 'files/*'
      - 'runtimes/text/*'
      - '.github/workflows/build-text.yml'
jobs:
  build-text:
    name: build-text
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Files
        run: cp files/* runtimes/text/
      - name: Build Image
        uses: docker/build-push-action@v1.0.1
        with:
          repository: pnoj/executor-text
          path: runtimes/text
          add_git_labels: true
          tag_with_sha: true
          tags: latest
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
