name: build-haskell
on:
  push:
    branches:
      - master
    paths:
      - 'files/*'
      - 'runtimes/haskell/*'
      - '.github/workflows/build-haskell.yml'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy files
        run: cp files/* runtimes/haskell/
      - name: Build Image
        uses: docker/build-push-action@v1.0.1
        with:
          repository: pnoj/executor-haskell
          path: runtimes/haskell
          add_git_labels: true
          tag_with_sha: true
          tags: latest
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
